version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_db:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.8.1
    restart: always
    user: root
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: zoC8-_2E7-ND4I6aRwt_F38Igd-F0-7EusToSlqxxHg=
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      # Configurações de email
      AIRFLOW__EMAIL__EMAIL_BACKEND: airflow.utils.email.send_email_smtp
      AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
      AIRFLOW__SMTP__SMTP_STARTTLS: 'true'
      AIRFLOW__SMTP__SMTP_SSL: 'false'
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_USER: seu-email
      AIRFLOW__SMTP__SMTP_PASSWORD: sua-senha
      AIRFLOW__SMTP__SMTP_MAIL_FROM: leozancheta@gmail.com
    volumes:
      - ../dags:/opt/airflow/dags
      - ../scripts:/opt/airflow/scripts
      - ../data:/opt/airflow/data
      - ../dataquality:/opt/airflow/dataquality
      - ../requirements.txt:/opt/airflow/requirements.txt
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - airflow-scheduler
    command: >
      bash -c "
        echo 'Configurando permissões...'
        chmod -R 777 /opt/airflow
        echo 'Instalando dependências...'
        pip install -r /opt/airflow/requirements.txt
        echo 'Iniciando webserver...'
        airflow webserver
      "

  airflow-scheduler:
    image: apache/airflow:2.8.1
    restart: always
    user: root
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: zoC8-_2E7-ND4I6aRwt_F38Igd-F0-7EusToSlqxxHg=
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      # Configurações de email
      AIRFLOW__EMAIL__EMAIL_BACKEND: airflow.utils.email.send_email_smtp
      AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
      AIRFLOW__SMTP__SMTP_STARTTLS: 'true'
      AIRFLOW__SMTP__SMTP_SSL: 'false'
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_USER: seu-email
      AIRFLOW__SMTP__SMTP_PASSWORD: sua-senha
      AIRFLOW__SMTP__SMTP_MAIL_FROM: leozancheta@gmail.com
    volumes:
      - ../dags:/opt/airflow/dags
      - ../scripts:/opt/airflow/scripts
      - ../data:/opt/airflow/data
      - ../dataquality:/opt/airflow/dataquality
      - ../requirements.txt:/opt/airflow/requirements.txt
    depends_on:
      - postgres
    command: >
      bash -c "
        echo 'Configurando permissões...'
        chmod -R 777 /opt/airflow
        echo 'Instalando dependências...'
        pip install -r /opt/airflow/requirements.txt
        echo 'Inicializando banco de dados...'
        airflow db init
        echo 'Criando usuário admin...'
        airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin || echo 'Usuário já existe'
        echo 'Iniciando scheduler...'
        airflow scheduler
      "

volumes:
  postgres_db:
